### ISSUE TITLE
Twitch now requires confirmation code sent to mail every time you login from a new place

### ISSUE THREAD

**Issue by ahmedtds** [Sleepydragn1/twitchAFK#1]
Can you update this to work with latest Twitch changes please?

Logging with username and password is not possible anymore because Twitch now requires you to enter confirmation code sent to mail when a cookie is not saved. And sometimes it asks some kind of captcha on top of that.

Can you make it so we can specify cookie or we can enter the required code and continue?

**Comment by Sleepydragn1** [comment]
Pausing to enter an email code in is _probably_ pretty easy to implement, but I'm not entirely sure about being able to scrape a cookie and use it. I'll take a look later and see how feasible it is.

Also, I probably need to update the way that the script selects the relevant username and password boxes anyways, so I'll do that at the same time.
