### ISSUE TITLE
headless linux machine?

### ISSUE THREAD

**Issue by HaxXorHardy** [Sleepydragn1/twitchAFK#13]
is it possible to get this running on an headless linux machine?

**Comment by Sleepydragn1** [comment]
SlimerJS, Firefox 59.0.3, and this script should all be Linux compatible, although I haven't tested them myself. 

**However,** you might run into a stumbling block with Twitch's CAPTCHA system, which isn't something this script handles automatically for obvious reasons. Further, the circumstances in which Twitch gives you a CAPTCHA versus when it does not are something I can only speculate on. If you do get a CAPTCHA, the script will note "Further authentication required. Waiting 10 minutes for user input..." in the command line output/logs. 

I suspect you could get around it by copying over a profile that is already logged in over to the headless machine, but again, this isn't something I have tested.

**Comment by Sleepydragn1** [comment]
I've added the ability to import and export cookies, which should make running twitchAFK fully possible on headless machines. See [this](https://github.com/Sleepydragn1/twitchAFK#importing-cookies) for more information.
