### ISSUE TITLE
Using Auth Cookies for Login

### ISSUE THREAD

**Issue by Xiseous** [Sleepydragn1/twitchAFK#14]
Running this script on a headless server on Linux is almost impossible due to Captcha, is there any chance you could integrate the use of the auth cookie as a work around?

**Comment by Sleepydragn1** [comment]
I can look into it.

**Comment by Sleepydragn1** [comment]
I've added a feature that should allow you to do this, even if it's through a slightly annoying process. See [this](https://github.com/Sleepydragn1/twitchAFK#importing-cookies) for more information, and let me know if you have any issues.
