### ISSUE TITLE
I'm one of those idiots trying to figure this out with a dum dum brain

### ISSUE THREAD

**Issue by MindlessKibbles** [Sleepydragn1/twitchAFK#15]
Aight. So. Added windows environmental variables. Have slimerjs and Firefox 59.0.3 in the same directory just in case that was my problem. Successfully creating new profiles. When I run "slimerjs -P ProfileName twitchAFK.js" having set the appropriate channel in the config file, it runs, I assume, but nothing pops up(running without headless as I haven't gotten it to work yet.) As a sidenote, when I attempt to launch twitch within the 59.0.3 browser, firefox crashes.

![whats happening here](https://user-images.githubusercontent.com/73566628/97472912-c1712e00-1920-11eb-8779-d45c03a330ee.png)

If I've not answered the right questions, please let me know.

**Comment by Sleepydragn1** [comment]
A couple of clarifying questions:

- Does the Firefox 59.0.3 install work on other pages besides Twitch? In particular, have you tried other video streaming sites like YouTube?
- Do you have any logs from the attempts to run the script?
- Does running twitchAFK without a profile (i.e. `slimerJS twitchAFK.js`) work?
- Is the Firefox 59.0.3 install in a separate folder from SlimerJS? Both SlimerJS and Firefox have files named "application.ini" and "omni.ja" and I have to assume that installing them in the same folder would cause problems.

Sorry if some of these sound dumb, but I need to cover all of my bases.

**Comment by MindlessKibbles** [comment]
It does work on other pages, including YouTube. I've reinstalled Firefox 59.0.3 to a new directory. I reverted back to all original versions of slimerjs files. Then I reverted to the unedited files for twitchAFK.
Edit: resolved the permission denied issue, as well as getting twitch.tv to open in firefox, but still fails to actually run the script

<img width="455" alt="example1" src="https://user-images.githubusercontent.com/73566628/97899410-44bac700-1d07-11eb-9919-66b899bf74d9.png">

When I run, I get no errors. There doesn't seem to be a log folder.
Ran with --debug and got this:
<img width="442" alt="example2" src="https://user-images.githubusercontent.com/73566628/97901218-dfb4a080-1d09-11eb-800d-4592e883094d.png">


I'm sure I've probably messed something up or have a system issue somewhere. Are there any prerequisites that I might be missing to run slimerjs in conjunction with firefox 59.0.3?

**Comment by Sleepydragn1** [comment]
Have you tried running the script outside of Cygwin? I can't think of any reason why it wouldn't work with it, but I would certainly try running it on Windows' cmd or PowerShell if you haven't already.

Otherwise, try running this basic SlimerJS script, which was slightly paired down from the example script on the SlimerJS main page:
```
var webpage = require('webpage').create();
webpage
  .open('http://twitch.tv') // loads a page
  .then(function(){ // executed after loading
    webpage.viewportSize =
        { width:1000, height:800 };
	console.log("Is this working?");
  });
```

Save it as something like "test.js" and run ``slimerjs test.js``.

It should just pop up the Twitch homepage, resize itself, and then output a message to the console. If it works, then we know it's some sort of issue with twitchAFK. If it doesn't, then it's some sort of issue with SlimerJS.

**EDIT:** Also, to answer your original question, as far as I'm aware there's no other prerequisites for SlimerJS or Firefox.

**Comment by MindlessKibbles** [comment]
You're the bomb. I'm dumb af. Trying PS instead of Cygwin worked right off the bat(pun intended.) Now just waiting for an alien abduction to complete my 2020 bingo card.

**Comment by Sleepydragn1** [comment]
Glad to hear that worked. 

I wasn't looking forward to learning that my script was fundamentally broken in some way, and frankly any outcome where I don't have to slowly piece through my code to learn what went horribly wrong is a good outcome in my mind.

Anyways, thanks for being patient, and if you have any other problems, feel free to open another issue.
