### ISSUE TITLE
Twitch channel points

### ISSUE THREAD

**Issue by ahmedtds** [Sleepydragn1/twitchAFK#2]
Can you update this to work with new Twitch Channel Points please? Also auto-collecting bonus channel points. You know they require to click manually.

**Comment by Sleepydragn1** [comment]
This seems doable and like it'd be a useful feature, but I'll need to look into it more carefully.

**Comment by ahmedtds** [comment]
Thanks a lot for responding and working on it <3

Code on these extensions may be useful when you are looking into it:
https://github.com/xinitrc-dev/twitch-points-autoclicker
https://github.com/trmcnvn/twitch-channel-points
https://github.com/huigovnomuravei/twitch-points-claimer
