### ISSUE TITLE
MultiDrops

### ISSUE THREAD

**Issue by mclooter** [Sleepydragn1/twitchAFK#3]
Hello, i want to farm drops because i want to play Valorant, i wanna use your script, but can you make it possible to add 10/100 accounts for farm? Not only one.
If it's already possible - im sorry, im blind

**Comment by Sleepydragn1** [comment]
As it is right now, you'd can do this, but you'd need to use multiple SlimerJS profiles and multiple twitchAFKConfig.js files to achieve this. 

So the setup would be something like this:

1. slimerjs -CreateProfile profile1
2. Change twitchAFKConfig.js to reflect the first account's username and password.
3. slimerjs -P profile1 twitchAFK.js [Valorant channel name here]
4. You'll likely need to fill out a CAPTCHA next.
5. slimerjs -CreateProfile profile2
6. Change twitchAFKConfig.js to reflect the second account's username and password.
7. slimerjs -P profile2 twitchAFK.js [Valorant channel name here]
8. You'll likely need to fill out a CAPTCHA next.
9. So on, and so forth.

It's tedious, but possible.

Within the next couple of days, I'll try to add in command line arguments to specify alternate config files and username and passwords. This'll make that process easier, but you'll still likely have to fill out a CAPTCHA every time, preventing it from being fully automated.
