### ISSUE TITLE
InvalidStateError spam. 

### ISSUE THREAD

**Issue by frapeil** [Sleepydragn1/twitchAFK#4]
```
Script Error: InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
       Stack:
         -> https://uaw3vx1k0ttq74u9b2zfvt768eebh1.ext-twitch.tv/uaw3vx1k0ttq74u9b2zfvt768eebh1/0.4.1/785a6a84875725a80bcc072b2649a844/viewer.js: 1 (in function value)
         -> https://uaw3vx1k0ttq74u9b2zfvt768eebh1.ext-twitch.tv/uaw3vx1k0ttq74u9b2zfvt768eebh1/0.4.1/785a6a84875725a80bcc072b2649a844/viewer.js: 1 (in function value/<)
```

A note: multiple profiles are being ran with proxies connected to each instance.

**Comment by Sleepydragn1** [comment]
Can you be more specific about when/where this error is occurring? Is it before the script can begin executing? Do you have any logs? What OS are you running?

**Comment by Sleepydragn1** [comment]
Since you haven't responded back with any additional information in well over a month, I'm going to close this issue. Feel free to comment back if you're still having this problem and have additional information to help narrow the search.
