### ISSUE TITLE
Windows Task Schedule - Help

### ISSUE THREAD

**Issue by xe1os** [Sleepydragn1/twitchAFK#6]
Hi @Sleepydragn1,

Could you please help in scheduling twitchafk task in Task Scheduler for Windows 10.

It would be really helpful.

**Comment by Sleepydragn1** [comment]
I'll add an example section to the README on task scheduling when I have some free time.

**Comment by xe1os** [comment]
@Sleepydragn1 thank you :)

**Comment by Sleepydragn1** [comment]
[This new section of the README should help serve as an example for you.](https://github.com/Sleepydragn1/twitchAFK#task-scheduler-example)

If it's still not clear, feel free to comment back to ask for further help.
