### ISSUE TITLE
volume in headless window

### ISSUE THREAD

**Issue by imaxisXD** [Sleepydragn1/twitchAFK#9]
as u all know to get drop u need to enable the volume of the stream u cant mute it as it will be counted as afk viewer so can u add setting to adjust the stream volume

**Comment by Sleepydragn1** [comment]
> u cant mute it as it will be counted as afk viewer

While I know that there's a lot of posts out there claiming that this is case, I'm absolutely certain that muting the stream doesn't prevent you from getting drops. 

Despite the fact that this script mutes streams automatically, I've been getting drops consistently for over a year using it, including one as recently as a couple weeks ago. Even before I started using this script, I was able to get drops while the streams I was watching were muted. I can also report that I have friends that were also able to get drops while their stream was muted.

So, from my point of view it's entirely unnecessary to have the stream unmuted. If you're still set on it, I'll add in an option to enable/disable stream volume, but I cannot stress enough that it doesn't preclude getting drops.
